package utils

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestIndent(t *testing.T) {
	// Generated by chat.openai.com
	input := `In the quiet town of Willowbrook, nestled between rolling hills and lush greenery, life
unfolded at a leisurely pace. The townsfolk, with their friendly smiles and welcoming demeanor
went about their daily routines. The aroma of freshly baked bread wafted through the air from
the local bakery, while children played in the park, their laughter echoing against the backdrop
of a clear blue sky. Willowbrook, a place where time seemed to slow down, embraced a sense of
tranquility that captivated anyone lucky enough to experience its charm.`

	cases := []struct {
		name   string
		input  string
		prefix string
		want   string
	}{
		{
			name:   "no-prefix",
			input:  input,
			prefix: "",
			want:   input,
		},
		{
			name:   "string-prefix",
			input:  input,
			prefix: ">",
			want: `>In the quiet town of Willowbrook, nestled between rolling hills and lush greenery, life
>unfolded at a leisurely pace. The townsfolk, with their friendly smiles and welcoming demeanor
>went about their daily routines. The aroma of freshly baked bread wafted through the air from
>the local bakery, while children played in the park, their laughter echoing against the backdrop
>of a clear blue sky. Willowbrook, a place where time seemed to slow down, embraced a sense of
>tranquility that captivated anyone lucky enough to experience its charm.`,
		},
		{
			name:   "tab-prefix",
			input:  input,
			prefix: ">\t",
			want: `>	In the quiet town of Willowbrook, nestled between rolling hills and lush greenery, life
>	unfolded at a leisurely pace. The townsfolk, with their friendly smiles and welcoming demeanor
>	went about their daily routines. The aroma of freshly baked bread wafted through the air from
>	the local bakery, while children played in the park, their laughter echoing against the backdrop
>	of a clear blue sky. Willowbrook, a place where time seemed to slow down, embraced a sense of
>	tranquility that captivated anyone lucky enough to experience its charm.`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			actual := Indent(tc.input, tc.prefix)
			assert.Equal(t, tc.want, actual)
		})
	}
}
